import { contextBridge, ipcRenderer } from 'electron';
import type { IndexProgress } from '@alchemist-coder/core';
import { Channels, type AlchemistApi, type ArenaTask, type AutomationState, type BackupStatus, type BoardData, type BotTeam, type PlanUsage, type RunnerEventMessage } from '../shared/api';

const subscribe = <T>(channel: string, listener: (payload: T) => void) => {
  const handler = (_event: unknown, payload: T) => listener(payload);
  ipcRenderer.on(channel, handler);
  return () => {
    ipcRenderer.removeListener(channel, handler);
  };
};

const api: AlchemistApi = {
  info: () => ipcRenderer.invoke(Channels.info),
  getSettings: () => ipcRenderer.invoke(Channels.getSettings),
  setSettings: (patch) => ipcRenderer.invoke(Channels.setSettings, patch),
  projects: () => ipcRenderer.invoke(Channels.projects),
  openFolder: (title) => ipcRenderer.invoke(Channels.openFolder, title),
  chooseFolder: (title, defaultPath) => ipcRenderer.invoke(Channels.chooseFolder, title, defaultPath),
  createProject: (parent, name, git) => ipcRenderer.invoke(Channels.createProject, parent, name, git),
  marketingLoad: (cwd) => ipcRenderer.invoke(Channels.marketingLoad, cwd),
  marketingSave: (cwd, data) => ipcRenderer.invoke(Channels.marketingSave, cwd, data),
  marketingDrafts: (cwd) => ipcRenderer.invoke(Channels.marketingDrafts, cwd),
  boardLoad: () => ipcRenderer.invoke(Channels.boardLoad),
  boardSave: (data, seenAt) => ipcRenderer.invoke(Channels.boardSave, data, seenAt),
  onBoardChanged: (listener) => subscribe<BoardData>(Channels.boardChanged, listener),
  automations: () => ipcRenderer.invoke(Channels.automations),
  saveAutomation: (automation) => ipcRenderer.invoke(Channels.automationSave, automation),
  createAutomation: (input) => ipcRenderer.invoke(Channels.automationCreate, input),
  reviseAutomation: (id, change) => ipcRenderer.invoke(Channels.automationRevise, id, change),
  deleteAutomation: (id) => ipcRenderer.invoke(Channels.automationDelete, id),
  setAutomationEnabled: (id, on) => ipcRenderer.invoke(Channels.automationEnable, id, on),
  runAutomation: (id) => ipcRenderer.invoke(Channels.automationRun, id),
  stopAutomationRun: (runId) => ipcRenderer.invoke(Channels.automationStop, runId),
  answerAutomation: (runId, askId, choice) => ipcRenderer.invoke(Channels.automationAnswer, runId, askId, choice),
  onAutomationChanged: (listener) => subscribe<AutomationState>(Channels.automationChanged, listener),
  automationSettings: () => ipcRenderer.invoke(Channels.automationSettings),
  setAutomationOptions: (patch) => ipcRenderer.invoke(Channels.automationOptions, patch),
  connectTelegram: (token) => ipcRenderer.invoke(Channels.telegramConnect, token),
  pairTelegram: () => ipcRenderer.invoke(Channels.telegramPair),
  testTelegram: () => ipcRenderer.invoke(Channels.telegramTest),
  actionsList: (cwd) => ipcRenderer.invoke(Channels.actionsList, cwd),
  actionsCreate: (cwd, example) => ipcRenderer.invoke(Channels.actionsCreate, cwd, example),
  subagents: (cwd) => ipcRenderer.invoke(Channels.subagents, cwd),
  sessions: (projectId, favoritesOnly) => ipcRenderer.invoke(Channels.sessions, projectId, favoritesOnly),
  recentSessions: (projectIds, perProject) => ipcRenderer.invoke(Channels.recentSessions, projectIds, perProject),
  session: (id) => ipcRenderer.invoke(Channels.session, id),
  agentTree: (id) => ipcRenderer.invoke(Channels.agentTree, id),
  transcript: (sessionId, agentId, offset, limit) => ipcRenderer.invoke(Channels.transcript, sessionId, agentId, offset, limit),
  search: (query, projectId) => ipcRenderer.invoke(Channels.search, query, projectId),
  setFavorite: (id, favorite) => ipcRenderer.invoke(Channels.setFavorite, id, favorite),
  renameSession: (id, title) => ipcRenderer.invoke(Channels.renameSession, id, title),
  hideSession: (id, hidden) => ipcRenderer.invoke(Channels.hideSession, id, hidden),
  hiddenSessions: () => ipcRenderer.invoke(Channels.hiddenSessions),
  trashSession: (id) => ipcRenderer.invoke(Channels.trashSession, id),
  revealSession: (id) => ipcRenderer.invoke(Channels.revealSession, id),
  indexStatus: () => ipcRenderer.invoke(Channels.indexStatus),
  onIndexProgress: (listener) => subscribe<IndexProgress>(Channels.progress, listener),
  onSessionsChanged: (listener) => subscribe<string[]>(Channels.changed, listener),
  runnerCatalog: () => ipcRenderer.invoke(Channels.runnerCatalog),
  setProviderCredential: (providerId, value) => ipcRenderer.invoke(Channels.setProviderCredential, providerId, value),
  startRun: (request) => ipcRenderer.invoke(Channels.startRun, request),
  sendToRun: (runId, text, images) => ipcRenderer.invoke(Channels.sendToRun, runId, text, images),
  stopRun: (runId) => ipcRenderer.invoke(Channels.stopRun, runId),
  interruptRun: (runId) => ipcRenderer.invoke(Channels.interruptRun, runId),
  respondToRun: (runId, requestId, choiceId) => ipcRenderer.invoke(Channels.respondToRun, runId, requestId, choiceId),
  answerRun: (runId, requestId, answer) => ipcRenderer.invoke(Channels.answerRun, runId, requestId, answer),
  configureRun: (runId, change) => ipcRenderer.invoke(Channels.configureRun, runId, change),
  previewUrl: (root, path) => ipcRenderer.invoke(Channels.previewUrl, root, path),
  onPreviewBlocked: (listener) => subscribe<string>(Channels.previewBlocked, listener),
  hubInventory: (cwd) => ipcRenderer.invoke(Channels.hubInventory, cwd),
  hubPlanInstall: (name, cwd) => ipcRenderer.invoke(Channels.hubPlanInstall, name, cwd),
  hubInstall: (name, agents, cwd) => ipcRenderer.invoke(Channels.hubInstall, name, agents, cwd),
  hubUnify: (cwd) => ipcRenderer.invoke(Channels.hubUnify, cwd),
  exportSession: (id, format) => ipcRenderer.invoke(Channels.exportSession, id, format),
  backupStatus: () => ipcRenderer.invoke(Channels.backupStatus),
  backupChoose: () => ipcRenderer.invoke(Channels.backupChoose),
  backupRun: () => ipcRenderer.invoke(Channels.backupRun),
  backupSetAuto: (auto) => ipcRenderer.invoke(Channels.backupSetAuto, auto),
  backupOpen: () => ipcRenderer.invoke(Channels.backupOpen),
  onBackupStatus: (listener) => subscribe<BackupStatus>(Channels.backupChanged, listener),
  planUsage: (refresh) => ipcRenderer.invoke(Channels.planUsage, refresh === true),
  onUsageChanged: (listener) => subscribe<PlanUsage>(Channels.usageChanged, listener),
  showMenu: (items) => ipcRenderer.invoke(Channels.showMenu, items),
  onAppCommand: (listener) => subscribe<string>(Channels.appCommand, listener),
  revealPath: (path) => ipcRenderer.invoke(Channels.revealPath, path),
  copyText: (text) => ipcRenderer.invoke(Channels.copyText, text),
  reviews: (cwd) => ipcRenderer.invoke(Channels.reviews, cwd),
  reviewFile: (id, path) => ipcRenderer.invoke(Channels.reviewFile, id, path),
  reviewKeep: (id, path, baseline, basedOn) => ipcRenderer.invoke(Channels.reviewKeep, id, path, baseline, basedOn),
  reviewUndo: (id, path, content, basedOn) => ipcRenderer.invoke(Channels.reviewUndo, id, path, content, basedOn),
  reviewDismiss: (id) => ipcRenderer.invoke(Channels.reviewDismiss, id),
  tasks: (cwd) => ipcRenderer.invoke(Channels.tasks, cwd),
  createTask: (cwd, prompt) => ipcRenderer.invoke(Channels.createTask, cwd, prompt),
  planTask: (id, planner) => ipcRenderer.invoke(Channels.planTask, id, planner),
  editTask: (id, edit) => ipcRenderer.invoke(Channels.editTask, id, edit),
  startTask: (id, choices) => ipcRenderer.invoke(Channels.startTask, id, choices),
  stopTask: (id) => ipcRenderer.invoke(Channels.stopTask, id),
  taskDiff: (id, contestantId, path) => ipcRenderer.invoke(Channels.taskDiff, id, contestantId, path),
  mergeTask: (id, contestantId, squash) => ipcRenderer.invoke(Channels.mergeTask, id, contestantId, squash),
  discardTask: (id) => ipcRenderer.invoke(Channels.discardTask, id),
  removeTask: (id) => ipcRenderer.invoke(Channels.removeTask, id),
  onTaskChanged: (listener) => subscribe<ArenaTask>(Channels.taskChanged, listener),
  botConfigs: () => ipcRenderer.invoke(Channels.botConfigs),
  saveBotConfig: (config) => ipcRenderer.invoke(Channels.saveBotConfig, config),
  deleteBotConfig: (id) => ipcRenderer.invoke(Channels.deleteBotConfig, id),
  addStarterBots: (agent, starters) => ipcRenderer.invoke(Channels.addStarterBots, agent, starters),
  orgSettings: () => ipcRenderer.invoke(Channels.orgSettings),
  saveOrgSettings: (settings) => ipcRenderer.invoke(Channels.saveOrgSettings, settings),
  ensureOrg: (agent, starters) => ipcRenderer.invoke(Channels.ensureOrg, agent, starters),
  botTeams: () => ipcRenderer.invoke(Channels.botTeams),
  startTeam: (request) => ipcRenderer.invoke(Channels.startTeam, request),
  messageBot: (teamId, botId, text) => ipcRenderer.invoke(Channels.messageBot, teamId, botId, text),
  stopBot: (teamId, botId) => ipcRenderer.invoke(Channels.stopBot, teamId, botId),
  deleteTeam: (teamId) => ipcRenderer.invoke(Channels.deleteTeam, teamId),
  renameTeam: (teamId, title) => ipcRenderer.invoke(Channels.renameTeam, teamId, title),
  answerPlan: (teamId, answer) => ipcRenderer.invoke(Channels.answerPlan, teamId, answer),
  botChanges: (teamId, botId) => ipcRenderer.invoke(Channels.botChanges, teamId, botId),
  botDiff: (teamId, botId) => ipcRenderer.invoke(Channels.botDiff, teamId, botId),
  applyBotWork: (teamId, botId) => ipcRenderer.invoke(Channels.applyBotWork, teamId, botId),
  onBotTeamChanged: (listener) => subscribe<BotTeam>(Channels.botTeamChanged, listener),
  onRunnerEvent: (listener) => subscribe<RunnerEventMessage>(Channels.runnerEvent, listener),
  listDir: (dir) => ipcRenderer.invoke(Channels.listDir, dir),
  readFile: (path) => ipcRenderer.invoke(Channels.readFile, path),
  writeFile: (path, text) => ipcRenderer.invoke(Channels.writeFile, path, text),
  createEntry: (dir, name, kind) => ipcRenderer.invoke(Channels.createEntry, dir, name, kind),
  renameEntry: (path, name) => ipcRenderer.invoke(Channels.renameEntry, path, name),
  trashEntry: (path) => ipcRenderer.invoke(Channels.trashEntry, path),
  gitStatus: (cwd) => ipcRenderer.invoke(Channels.gitStatus, cwd),
  gitOverview: (cwd) => ipcRenderer.invoke(Channels.gitOverview, cwd),
  gitAction: (cwd, action, arg) => ipcRenderer.invoke(Channels.gitAction, cwd, action, arg),
  gitCommit: (cwd, files, message, push) => ipcRenderer.invoke(Channels.gitCommit, cwd, files, message, push),
  searchFiles: (cwd, query) => ipcRenderer.invoke(Channels.searchFiles, cwd, query),
  transcriptImage: (sessionId, agentId, offset, n) => ipcRenderer.invoke(Channels.transcriptImage, sessionId, agentId, offset, n),
  slashCommands: (harnessId, cwd) => ipcRenderer.invoke(Channels.slashCommands, harnessId, cwd),
  gitHead: (cwd, path) => ipcRenderer.invoke(Channels.gitHead, cwd, path),
  terminalAvailable: () => ipcRenderer.invoke(Channels.terminalAvailable),
  terminalShells: () => ipcRenderer.invoke(Channels.terminalShells),
  createTerminal: (cwd, cols, rows, shell) => ipcRenderer.invoke(Channels.createTerminal, cwd, cols, rows, shell),
  terminalLinks: (cwd, candidates) => ipcRenderer.invoke(Channels.terminalLinks, cwd, candidates),
  writeTerminal: (id, data) => ipcRenderer.send(Channels.writeTerminal, id, data),
  resizeTerminal: (id, cols, rows) => ipcRenderer.send(Channels.resizeTerminal, id, cols, rows),
  killTerminal: (id) => ipcRenderer.send(Channels.killTerminal, id),
  onTerminalData: (listener) => subscribe<{ id: string; data: string }>(Channels.terminalData, listener),
  onTerminalExit: (listener) => subscribe<{ id: string; code: number }>(Channels.terminalExit, listener),
  importTheme: () => ipcRenderer.invoke(Channels.importTheme),
  searchThemes: (query) => ipcRenderer.invoke(Channels.searchThemes, query),
  installTheme: (namespace, name) => ipcRenderer.invoke(Channels.installTheme, namespace, name),
  rendered: () => ipcRenderer.send(Channels.rendered),
  setAttention: (attention) => ipcRenderer.send(Channels.setAttention, attention),
};

contextBridge.exposeInMainWorld('alchemist', api);
